doctrine_migrations:
    migrations_paths:
        # namespace is arbitrary but should be different from App\Migrations
        # as migrations classes should NOT be autoloaded
        'DoctrineMigrations': '%kernel.project_dir%/migrations'
        'App\Modules\Authentication\Infrastructure\Persistence': '%kernel.project_dir%/src/Modules/Authentication/Infrastructure/Persistence'
        'App\Modules\Finance\Currency\Infrastructure\Persistence': '%kernel.project_dir%/src/Modules/Finance/Currency/Infrastructure/Persistence'
        'App\Modules\Finance\Wallet\Infrastructure\Persistence': '%kernel.project_dir%/src/Modules/Finance/Wallet/Infrastructure/Persistence'
        'App\Modules\Finance\Expense\Infrastructure\Persistence': '%kernel.project_dir%/src/Modules/Finance/Expense/Infrastructure/Persistence'
    enable_profiler: '%kernel.debug%'
