nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['*']
        allow_methods: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization', 'X-Auth-Token']
        expose_headers: ['Link', 'X-Total-Count', 'X-Total-Pages']
        max_age: 3600
