#services:
#    App\Modules\Minecraft\Item\Service\ItemFetcher:
#        autowire: true
#        autoconfigure: true
#
#    App\Modules\Minecraft\Item\Service\ItemServiceInterface: '@App\Modules\Minecraft\Item\Service\ItemFetcher'