index:
    path: /
    controller: App\Controller\MainPageController::index

work.index:
    path: /work
    controller: App\Controller\WorkController::index

work.store:
    path: /work/store
    controller: App\Controller\WorkController::store

work.update:
    path: /work/{id}/update
    controller: App\Controller\WorkController::update

work.remove:
    path: /work/{id}/remove
    controller: App\Controller\WorkController::remove

project.store:
    path: /work/project/store
    controller: App\Controller\ProjectController::store

minecraft_api:
    prefix: api/minecraft
    name_prefix: minecraft.
    resource: '../src/Modules/Minecraft/routes.yml'

auth_api:
    prefix: api/auth
    name_prefix: auth.
    resource: '../src/Modules/Authentication/Infrastructure/Http/routes.yml'
