imports:
    - { resource: '@ItemModule/Resources/config/services.yaml' }
    - { resource: '@CraftCalculatorModule/Resources/config/services.yaml' }

parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    Framework\:
        resource: '../framework/'

    App\Service\LinkService:
        autoconfigure: true
        arguments:
            $links: [ [ 'MINECRAFT_FRONT', "%env(MINECRAFT_FRONT)%" ] ]

    App\Service\LinkServiceInterface: '@App\Service\LinkService'

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'
            - '@ItemModule/Entity/'
            - '@ItemModule/Request/'
            - '@ItemModule/DTO/'
            - '@ItemModule/Search/'
            - '../src/Service/LinkService.php'

    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    App\Modules\Authentication\Infrastructure\Http\Controller\:
        resource: '../src/Modules/Authentication/Infrastructure/Http/Controller/'
        tags: [ 'controller.service_arguments' ]

    App\Modules\Finance\Currency\Infrastructure\Http\Controller\:
        resource: '../src/Modules/Finance/Currency/Infrastructure/Http/Controller/'
        tags: [ 'controller.service_arguments' ]

    App\Modules\Finance\Wallet\Infrastructure\Http\Controller\:
        resource: '../src/Modules/Finance/Wallet/Infrastructure/Http/Controller/'
        tags: [ 'controller.service_arguments' ]

    App\Modules\Finance\Expense\Infrastructure\Http\Controller\:
        resource: '../src/Modules/Finance/Expense/Infrastructure/Http/Controller/'
        tags: [ 'controller.service_arguments' ]

    App\Modules\Authentication\Infrastructure\Adapter\OrganizerAuthUserRepository:
        autoconfigure: true
        arguments:
            $organizerAuthLink: "%env(ORGANIZER_AUTH)%"
