services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Tests\:
        resource: '../tests/'
        exclude:
            -  '../tests/Modules/*/*/*/TestDoubles/QueryHandler/'


    App\Tests\Modules\Authentication\Integration\TestUtils\UserService:
        public: true
    App\Modules\Authentication\Application\Repository\ExternalUserRepository:
        public: true
        class: App\Tests\SharedInfrastructure\TestDoubles\ExternalUserRepositoryFake

    App\Tests\Modules\Finance\Currency\Integration\TestUtils\CurrencyService:
        public: true

    App\Tests\Modules\Finance\Wallet\Integration\TestUtils\WalletService:
        public: true

    App\Tests\Modules\Finance\Expense\Integration\TestUtils\ExpenseService:
        public: true