imports:
    - { resource: '@ItemModule/Resources/config/services.yaml' }
    - { resource: '@CraftCalculatorModule/Resources/config/services.yaml' }
    - { resource: '@YouTubeModule/Resources/config/services.yml' }

parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    Framework\:
        resource: '../framework/'

    App\Service\LinkService:
        autoconfigure: true
        arguments:
            $links: [ [ 'MINECRAFT_FRONT', "%env(MINECRAFT_FRONT)%" ] ]

    App\Service\LinkServiceInterface: '@App\Service\LinkService'

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'
            - '@ItemModule/Entity/'
            - '@ItemModule/Request/'
            - '@ItemModule/DTO/'
            - '@YouTubeModule/Request/'
            - '@YouTubeModule/Entity/'
            - '../src/Service/LinkService.php'

    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']
