imports:
    - { resource: '@ItemModule/Resources/config/services.yaml' }

parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    Framework\:
        resource: '../framework/'

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'
            - '@ItemModule/Entity/'
            - '@ItemModule/Request/'
            - '@ItemModule/DTO/'

    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']
