services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Tests\:
        resource: '../tests/'


    App\Tests\Modules\Authentication\Integration\TestUtils\UserService:
        public: true
    App\Modules\Authentication\Application\Repository\ExternalUserRepository:
        public: true

    App\Tests\Modules\Finance\Currency\Integration\TestUtils\CurrencyService:
        public: true