minecraft.item.get:
    path: minecraft/item/{id}
    methods: [GET]
    controller: App\Modules\Minecraft\Item\Controller\ItemController::fetch

minecraft.item.save:
    path: minecraft/item
    methods: [POST]
    controller: App\Modules\Minecraft\Item\Controller\ItemController::store