item.get:
    path: item/{id}
    methods: [GET]
    controller: App\Modules\Minecraft\Item\Controller\ItemController::fetch

item.getAll:
    path: item
    methods: [GET]
    controller: App\Modules\Minecraft\Item\Controller\ItemController::fetchAll

item.store:
    path: item
    methods: [POST]
    controller: App\Modules\Minecraft\Item\Controller\ItemController::store

item.delete:
    path: item/{id}
    methods: [DELETE]
    controller: App\Modules\Minecraft\Item\Controller\ItemController::delete


recipe.fetch:
    path: recipe/{id}
    methods: [GET]
    controller: App\Modules\Minecraft\Item\Controller\RecipeController::fetch

recipe.store:
    path: recipe
    methods: [POST]
    controller: App\Modules\Minecraft\Item\Controller\RecipeController::store